void foo () {
    return 5; // should fail
} 

void main () {}